<?php

/**
 * @file
 * Contains d7migrate.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function d7migrate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the d7migrate module.
    case 'help.page.d7migrate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migrate D7 to D8.') . '</p>';
      return $output;

    default:
  }
}
